site:
  name: CodeBridgeAI
  site: 'https://codebridge.ai.kr'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: 

# Default SEO metadata
metadata:
  title:
    default: CodeBridgeAI - Bridge to the Future World
    template: '%s — CodeBridgeAI'
  description: "코드와 사람을 잇는 다리, CodeBridgeAI. 코딩 교육, LMS, 디지털사이니지, AI 솔루션을 통해 지식과 기술을 연결합니다."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: CodeBridgeAI
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@codebridgeai'
    site: '@codebridgeai'
    cardType: summary_large_image

i18n:
  language: ko
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
